version: "3.8"
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8020:8000"
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3020:3000"
    #environment:
    #  - BACKEND_URL=http://<IP_ADDRESS>:<PORT> # Backend URL without trailing slash
    stdin_open: true
    tty: true
